In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
from sklearn import model_selection
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier

In [2]:
dataset=pd.read_csv('Exercise//NewspaperData.csv')
dataset.head()

Newspaper    daily   sunday
0       Baltimore Sun  391.952  488.506
1        Boston Globe  516.981  798.298
2       Boston Herald  355.628  235.084
3  Charlotte Observer  238.555  299.451
4   Chicago Sun Times  537.780  559.093

In [3]:
dataset=dataset.drop(columns=['Newspaper'],axis=1)
dataset.head()

daily   sunday
0  391.952  488.506
1  516.981  798.298
2  355.628  235.084
3  238.555  299.451
4  537.780  559.093

In [4]:
array=dataset.values
print(array)

[[ 391.952  488.506]
 [ 516.981  798.298]
 [ 355.628  235.084]
 [ 238.555  299.451]
 [ 537.78   559.093]
 [ 733.775 1133.249]
 [ 198.832  348.744]
 [ 252.624  417.779]
 [ 206.204  344.522]
 [ 231.177  323.084]
 [ 449.755  620.752]
 [ 288.571  423.305]
 [ 185.736  202.614]
 [1164.388 1531.527]
 [ 444.581  553.479]
 [ 412.871  685.975]
 [ 272.28   324.241]
 [ 781.796  983.24 ]
 [1209.225 1762.015]
 [ 825.512  960.308]
 [ 223.748  284.611]
 [ 354.843  407.76 ]
 [ 515.523  982.663]
 [ 220.465  557.   ]
 [ 337.672  440.923]
 [ 197.12   268.06 ]
 [ 133.239  262.048]
 [ 374.009  432.502]
 [ 273.844  338.355]
 [ 570.364  704.322]
 [ 391.286  585.681]
 [ 201.86   267.781]
 [ 321.626  408.343]
 [ 838.902 1165.567]]


In [9]:
import numpy as np
from sklearn import preprocessing
from sklearn import utils
X=np.array(array[:,0:1])
Y=np.array(array[:,1:])
print(X)

[[ 391.952]
 [ 516.981]
 [ 355.628]
 [ 238.555]
 [ 537.78 ]
 [ 733.775]
 [ 198.832]
 [ 252.624]
 [ 206.204]
 [ 231.177]
 [ 449.755]
 [ 288.571]
 [ 185.736]
 [1164.388]
 [ 444.581]
 [ 412.871]
 [ 272.28 ]
 [ 781.796]
 [1209.225]
 [ 825.512]
 [ 223.748]
 [ 354.843]
 [ 515.523]
 [ 220.465]
 [ 337.672]
 [ 197.12 ]
 [ 133.239]
 [ 374.009]
 [ 273.844]
 [ 570.364]
 [ 391.286]
 [ 201.86 ]
 [ 321.626]
 [ 838.902]]


In [10]:
X_train,X_test,Y_train,Y_test=model_selection.train_test_split(X,Y,test_size=0.20)
print(Y)

[[ 488.506]
 [ 798.298]
 [ 235.084]
 [ 299.451]
 [ 559.093]
 [1133.249]
 [ 348.744]
 [ 417.779]
 [ 344.522]
 [ 323.084]
 [ 620.752]
 [ 423.305]
 [ 202.614]
 [1531.527]
 [ 553.479]
 [ 685.975]
 [ 324.241]
 [ 983.24 ]
 [1762.015]
 [ 960.308]
 [ 284.611]
 [ 407.76 ]
 [ 982.663]
 [ 557.   ]
 [ 440.923]
 [ 268.06 ]
 [ 262.048]
 [ 432.502]
 [ 338.355]
 [ 704.322]
 [ 585.681]
 [ 267.781]
 [ 408.343]
 [1165.567]]


In [16]:
model=LinearRegression()
model.fit(X_train,Y_train)
ypred=model.predict(X_test)

In [17]:
print(ypred)

[[1590.30934315]
 [ 278.02044008]
 [ 553.64546718]
 [ 328.9912916 ]
 [ 505.83112899]
 [ 293.28541361]
 [ 793.773799  ]]


In [18]:
print(Y_test)

[[1531.527]
 [ 202.614]
 [ 585.681]
 [ 284.611]
 [ 235.084]
 [ 268.06 ]
 [ 704.322]]


In [19]:
from sklearn.metrics import r2_score
r2_score(Y_test,ypred)

0.9307245314217288

In [15]:
print(model.predict([[300]]))

[[431.23872321]]
